// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaProcinco.Entities.Entities
{
    public partial class tbAptitudesPorEmpleado
    {
        public int AptPe_Id { get; set; }
        public int? Apti_Id { get; set; }
        public int? Empl_Id { get; set; }
        public int AptPe_UsuarioCreacion { get; set; }
        public DateTime AptPe_FechaCreacion { get; set; }
        public int? AptPe_UsuarioModificacion { get; set; }
        public DateTime? AptPe_FechaModificacion { get; set; }
        public bool? AptPe_Estado { get; set; }

        public virtual tbUsuarios AptPe_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios AptPe_UsuarioModificacionNavigation { get; set; }
        public virtual tbAptitudes Apti { get; set; }
        public virtual tbEmpleados Empl { get; set; }
    }
}