// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaProcinco.Entities.Entities
{
    public partial class tbAptitudes
    {
        public tbAptitudes()
        {
            tbAptitudesPorEmpleado = new HashSet<tbAptitudesPorEmpleado>();
        }

        public int Apti_Id { get; set; }
        public string Apti_Descripcion { get; set; }
        public decimal? Apti_ValorMonetario { get; set; }
        public int Apti_UsuarioCreacion { get; set; }
        public DateTime Apti_FechaCreacion { get; set; }
        public int? Apti_UsuarioModificacion { get; set; }
        public DateTime? Apti_FechaModificacion { get; set; }
        public bool? Apti_Estado { get; set; }

        public virtual tbUsuarios Apti_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Apti_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbAptitudesPorEmpleado> tbAptitudesPorEmpleado { get; set; }
    }
}