// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaProcinco.Entities.Entities
{
    public partial class tbEmpresas
    {
        public int Empre_Id { get; set; }
        public string Empre_Descripcion { get; set; }
        public string Empre_Direccion { get; set; }
        public int Ciud_Id { get; set; }
        public int Empre_UsuarioCreacion { get; set; }
        public DateTime Empre_FechaCreacion { get; set; }
        public int? Empre_UsuarioModificacion { get; set; }
        public DateTime? Empre_FechaModificacion { get; set; }
        public bool? Empre_Estado { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
        public virtual tbUsuarios Empre_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Empre_UsuarioModificacionNavigation { get; set; }
    }
}
