// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaProcinco.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbInformeEmpleados = new HashSet<tbInformeEmpleados>();
            tbTitulosPorEmpleado = new HashSet<tbTitulosPorEmpleado>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int Empl_Id { get; set; }
        public string Empl_DNI { get; set; }
        public int? Carg_Id { get; set; }
        public string Empl_Nombre { get; set; }
        public string Empl_Apellido { get; set; }
        public string Empl_Correo { get; set; }
        public DateTime? Empl_FechaNacimiento { get; set; }
        public string Empl_Sexo { get; set; }
        public int? Estc_Id { get; set; }
        public string Empl_Direccion { get; set; }
        public string Ciud_id { get; set; }
        public int? Empl_UsuarioCreacion { get; set; }
        public DateTime? Empl_FechaCreacion { get; set; }
        public int? Empl_UsuarioModificacion { get; set; }
        public DateTime? Empl_FechaModificacion { get; set; }
        public bool? Empl_Estado { get; set; }
        public decimal? Empl_SalarioHora { get; set; }

        public virtual tbCargos Carg { get; set; }
        public virtual tbCiudades Ciud { get; set; }
        public virtual tbUsuarios Empl_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Empl_UsuarioModificacionNavigation { get; set; }
        public virtual tbEstadosCiviles Estc { get; set; }
        public virtual ICollection<tbInformeEmpleados> tbInformeEmpleados { get; set; }
        public virtual ICollection<tbTitulosPorEmpleado> tbTitulosPorEmpleado { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}