// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaProcinco.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int Estc_Id { get; set; }
        public string Estc_Descripcion { get; set; }
        public int Estc_UsuarioCreacion { get; set; }
        public DateTime Estc_FechaCreacion { get; set; }
        public int? Estc_UsuarioModificacion { get; set; }
        public DateTime? Estc_FechaModificacion { get; set; }
        public bool? Estc_Estado { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
        public virtual tbUsuarios Estc_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Estc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}