// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaProcinco.Entities.Entities
{
    public partial class tbPantallas
    {
        public tbPantallas()
        {
            tbPantallasPorRoles = new HashSet<tbPantallasPorRoles>();
        }

        public int Pant_Id { get; set; }
        public string Pant_Descripcion { get; set; }
        public int Pant_UsuarioCreacion { get; set; }
        public DateTime Pant_FechaCreacion { get; set; }
        public int? Pant_UsuarioModificacion { get; set; }
        public DateTime? Pant_FechaModificacion { get; set; }
        public bool? Pant_Estado { get; set; }
        [NotMapped]
        public string Creacion { get; set; }
        [NotMapped]
        public string Modificacion { get; set; }
        public virtual tbUsuarios Pant_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Pant_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
    }
}