// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaProcinco.Entities.Entities
{
    public partial class tbParticipantesPorCursoo
    {
        public int PaCur_Id { get; set; }
        public int Part_Id { get; set; }
        public int Curso_Id { get; set; }
        public bool PaCur_Estado { get; set; }
        public DateTime? PaCur_FechaCreacion { get; set; }
        public int PaCur_UsuarioCreacion { get; set; }
        public DateTime? PaCur_FechaModificacion { get; set; }
        public int? PaCur_UsuarioModificacion { get; set; }

        public virtual tbCursos Curso { get; set; }
        public virtual tbUsuarios PaCur_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios PaCur_UsuarioModificacionNavigation { get; set; }
        public virtual tbParticipantes Part { get; set; }
    }
}