// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaProcinco.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            InverseUsua_UsuarioCreacionNavigation = new HashSet<tbUsuarios>();
            InverseUsua_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbCargosCarg_UsuarioCreacionNavigation = new HashSet<tbCargos>();
            tbCargosCarg_UsuarioModificacionNavigation = new HashSet<tbCargos>();
            tbCategoriasCate_UsuarioCreacionNavigation = new HashSet<tbCategorias>();
            tbCategoriasCate_UsuarioModificacionNavigation = new HashSet<tbCategorias>();
            tbCiudadesCiud_UsuarioCreacionNavigation = new HashSet<tbCiudades>();
            tbCiudadesCiud_UsuarioModificacionNavigation = new HashSet<tbCiudades>();
            tbContenidoCont_UsuarioCreacionNavigation = new HashSet<tbContenido>();
            tbContenidoCont_UsuarioModificacionNavigation = new HashSet<tbContenido>();
            tbContenidoPorCursoConPc_UsuarioCreacionNavigation = new HashSet<tbContenidoPorCurso>();
            tbContenidoPorCursoConPc_UsuarioModificacionNavigation = new HashSet<tbContenidoPorCurso>();
            tbCursosCurso_UsuarioCreacionNavigation = new HashSet<tbCursos>();
            tbCursosCurso_UsuarioModificacionNavigation = new HashSet<tbCursos>();
            tbCursosImpartidosCurIm_UsuarioCreacionNavigation = new HashSet<tbCursosImpartidos>();
            tbCursosImpartidosCurIm_UsuarioModificacionNavigation = new HashSet<tbCursosImpartidos>();
            tbEmpleadosEmpl_UsuarioCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosEmpl_UsuarioModificacionNavigation = new HashSet<tbEmpleados>();
            tbEmpresasEmpre_UsuarioCreacionNavigation = new HashSet<tbEmpresas>();
            tbEmpresasEmpre_UsuarioModificacionNavigation = new HashSet<tbEmpresas>();
            tbEstadosCivilesEstc_UsuarioCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesEstc_UsuarioModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosEsta_UsuarioCreacionNavigation = new HashSet<tbEstados>();
            tbEstadosEsta_UsuarioModificacionNavigation = new HashSet<tbEstados>();
            tbPantallasPant_UsuarioCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPant_UsuarioModificacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPorRolesPaPr_UsuarioCreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesPaPr_UsuarioModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbParticipantesPart_UsuarioCreacionNavigation = new HashSet<tbParticipantes>();
            tbParticipantesPart_UsuarioModificacionNavigation = new HashSet<tbParticipantes>();
            tbRolesRole_UsuarioCreacionNavigation = new HashSet<tbRoles>();
            tbRolesRole_UsuarioModificacionNavigation = new HashSet<tbRoles>();
            tbTitulosPorEmpleadoTitPe_UsuarioCreacionNavigation = new HashSet<tbTitulosPorEmpleado>();
            tbTitulosPorEmpleadoTitPe_UsuarioModificacionNavigation = new HashSet<tbTitulosPorEmpleado>();
            tbTitulosTitl_UsuarioCreacionNavigation = new HashSet<tbTitulos>();
            tbTitulosTitl_UsuarioModificacionNavigation = new HashSet<tbTitulos>();
        }

        //NOTMAPPED
        [NotMapped]
        public string Role_Descripcion { get; set; }
        [NotMapped]
        public string correo { get; set; }
        [NotMapped]
        public string adminfalso { get; set; }
        [NotMapped]
        public string Empl_Nombre { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }

        [NotMapped]
        public string UsuarioModificacion { get; set; }
        [NotMapped]
        public string Usua_Admin1 { get; set; }


        public int Usua_Id { get; set; }
        public string Usua_Usuario { get; set; }
        public string Usua_Contraseña { get; set; }
        public bool? Usua_EsAdmin { get; set; }
        public int Role_Id { get; set; }
        public int? Usua_UsuarioCreacion { get; set; }
        public DateTime Usua_FechaCreacion { get; set; }
        public int? Usua_UsuarioModificacion { get; set; }
        public DateTime? Usua_FechaModificacion { get; set; }
        public bool? Usua_Estado { get; set; }
        public int? Empl_Id { get; set; }
        public string Usua_VerificarCorreo { get; set; }

        public virtual tbEmpleados Empl { get; set; }
        public virtual tbRoles Role { get; set; }
        public virtual tbUsuarios Usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargosCarg_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargosCarg_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriasCate_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriasCate_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesCiud_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesCiud_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbContenido> tbContenidoCont_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbContenido> tbContenidoCont_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbContenidoPorCurso> tbContenidoPorCursoConPc_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbContenidoPorCurso> tbContenidoPorCursoConPc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCursos> tbCursosCurso_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCursos> tbCursosCurso_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCursosImpartidos> tbCursosImpartidosCurIm_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCursosImpartidos> tbCursosImpartidosCurIm_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmpl_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmpl_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpresas> tbEmpresasEmpre_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpresas> tbEmpresasEmpre_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEstc_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEstc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPaPr_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPaPr_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbParticipantes> tbParticipantesPart_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbParticipantes> tbParticipantesPart_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRole_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRole_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbTitulosPorEmpleado> tbTitulosPorEmpleadoTitPe_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbTitulosPorEmpleado> tbTitulosPorEmpleadoTitPe_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbTitulos> tbTitulosTitl_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbTitulos> tbTitulosTitl_UsuarioModificacionNavigation { get; set; }
    }
}