// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaProcinco.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            InverseUsua_UsuarioCreacionNavigation = new HashSet<tbUsuarios>();
            InverseUsua_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbCargosCarg_UsuarioCreacionNavigation = new HashSet<tbCargos>();
            tbCargosCarg_UsuarioModificacionNavigation = new HashSet<tbCargos>();
            tbCiudadesCiud_UsuarioCreacionNavigation = new HashSet<tbCiudades>();
            tbCiudadesCiud_UsuarioModificacionNavigation = new HashSet<tbCiudades>();
            tbEmpleadosEmpl_UsuarioCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosEmpl_UsuarioModificacionNavigation = new HashSet<tbEmpleados>();
            tbEstadosCivilesEstc_UsuarioCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesEstc_UsuarioModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosEsta_UsuarioCreacionNavigation = new HashSet<tbEstados>();
            tbEstadosEsta_UsuarioModificacionNavigation = new HashSet<tbEstados>();
            tbPantallasPant_UsuarioCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPant_UsuarioModificacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPorRolesPaPr_UsuarioCreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesPaPr_UsuarioModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbRolesRole_UsuarioCreacionNavigation = new HashSet<tbRoles>();
            tbRolesRole_UsuarioModificacionNavigation = new HashSet<tbRoles>();
        }

        public int Usua_Id { get; set; }
        public string Usua_Usuario { get; set; }
        public string Usua_Contraseña { get; set; }
        public bool? Usua_EsAdmin { get; set; }
        public int Role_Id { get; set; }
        public int? Usua_UsuarioCreacion { get; set; }
        public DateTime Usua_FechaCreacion { get; set; }
        public int? Usua_UsuarioModificacion { get; set; }
        public DateTime? Usua_FechaModificacion { get; set; }
        public bool? Usua_Estado { get; set; }
        public int? Empl_Id { get; set; }
        public string Usua_VerificarCorreo { get; set; }

        public virtual tbEmpleados Empl { get; set; }
        public virtual tbRoles Role { get; set; }
        public virtual tbUsuarios Usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargosCarg_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargosCarg_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesCiud_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesCiud_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmpl_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmpl_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEstc_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEstc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPaPr_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPaPr_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRole_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRole_UsuarioModificacionNavigation { get; set; }
    }
}